<?php

namespace App\Console\Commands;

use Illuminate\Console\GeneratorCommand;

class TraitCommand extends GeneratorCommand
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $name = 'make:trait';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    protected $type = 'Trait';

    protected function getStub()
    {
        // TODO: Implement getStub() method.
        return __DIR__."/stubs/trait.stub";
    }


    protected function getDefaultNamespace($rootNamespace)
    {
        return $rootNamespace.'\Traits'; // TODO: Change the autogenerated stub
    }
}
